### PR TITLE
feat: Upgraded Claude 3.5 Sonnet

### PR DESCRIPTION
**Pull request by watany-dev**
Thank you for the wonderful plugin. I've written the functionality to run a new model with this.
https://aws.amazon.com/jp/blogs/aws/upgraded-claude-3-5-sonnet-from-anthropic-available-now-computer-use-public-beta-and-claude-3-5-haiku-coming-soon-in-amazon-bedrock/

### CODE REVIEW

**Comment by ismail** [comment]
Thanks for the patch! Fixes #16. I wonder if you should have `claude-3-5-sonnet-latest` alias and map it to the latest version?

```
❯ llm models | grep sonnet-latest
Anthropic Messages: claude-3-5-sonnet-latest (aliases: claude-3.5-sonnet, claude-3.5-sonnet-latest)
```

**Comment by alonw-cf** [comment]
Not sure if this is related, but I tried to manually set the bedrock_model_id and I'm getting "Invocation of model ID anthropic.claude-3-5-sonnet-20241022-v2:0 with on-demand throughput isn’t supported. Retry your request with the ID or ARN of an inference profile that contains this model.".

**Comment by alonw-cf** [comment]
> Not sure if this is related, but I tried to manually set the bedrock_model_id and I'm getting "Invocation of model ID anthropic.claude-3-5-sonnet-20241022-v2:0 with on-demand throughput isn’t supported. Retry your request with the ID or ARN of an inference profile that contains this model.".

For those interested, got this to work by specifying the ARN in the "Providers" page of Bedrock: `arn:aws:bedrock:us-east-1:<my AWS account id>:inference-profile/us.anthropic.claude-3-5-sonnet-20241022-v2:0`

**Comment by watany-dev** [comment]
@sblakey 
Is there anything I can do to help move this PR forward? I'd like to work on 3.5 haiku after this.

**Comment by sblakey** [comment]
I'm SO sorry about the delay on accepting this merge. Pulling it in and testing it, tonight.

**Comment by sblakey** [comment]
Merging as-is. I think there's value to @ismail's idea of some sort of a "latest" semantic version, but I want to keep that concept distinct from this merge.

**Pull request merged**
